stages:
  train_test_split:
    cmd: python scripts/split_test_train.py
    deps:
    - data/raw/SN1/train/
    outs:
    - data/interim/SN1/test/3band/
    - data/interim/SN1/test/8band/
    - data/interim/SN1/test/geojson/
    - data/interim/SN1/train_val/3band/
    - data/interim/SN1/train_val/8band/
    - data/interim/SN1/train_val/geojson/
    - data/interim/SN1/train/3band/
    - data/interim/SN1/train/8band/
    - data/interim/SN1/train/geojson/
    - data/interim/SN1/val/3band/
    - data/interim/SN1/val/8band/
    - data/interim/SN1/val/geojson/
  rasterize_3band:
    cmd: python scripts/rasterize_segments.py
    deps:
    - data/interim/SN1/test/3band/
    - data/interim/SN1/test/8band/
    - data/interim/SN1/test/geojson/
    - data/interim/SN1/train_val/3band/
    - data/interim/SN1/train_val/8band/
    - data/interim/SN1/train_val/geojson/
    - data/interim/SN1/train/3band/
    - data/interim/SN1/train/8band/
    - data/interim/SN1/train/geojson/
    - data/interim/SN1/val/3band/
    - data/interim/SN1/val/8band/
    - data/interim/SN1/val/geojson/
    outs:
    - data/interim/SN1/test/geo_raster_3band/
    - data/interim/SN1/train_val/geo_raster_3band/
    - data/interim/SN1/train/geo_raster_3band/
    - data/interim/SN1/val/geo_raster_3band/
  evaluate_UNet:
    cmd: python scripts/evaluate_model.py --output_fname unet_ptl_v5.csv --model_name UNet
    deps:
    - data/interim/SN1/test/3band/
    - data/interim/SN1/test/geo_raster_3band/
    - models/unet/unet_ptl_v5/checkpoints/best_model-unet-epoch=15-val_loss=0.09.ckpt
    outs:
    - data/output/metrics/unet_ptl_v5.csv
  evaluate_UNetFineTuned:
    cmd: python scripts/evaluate_model.py --output_fname unet_ft_v8.csv --model_name UNetFineTuned
    deps:
    - data/interim/SN1/test/3band/
    - data/interim/SN1/test/geo_raster_3band/
    - models/unet/unet_finetuned_v8/checkpoints/best_model-unet-epoch=03-val_loss=0.09.ckpt
    outs:
    - data/output/metrics/unet_ft_v8.csv
